### ISSUE TITLE
breastdb visibility issue

### ISSUE THREAD

**Issue by jedchan** [radiology-research/ispy2_mri#2]
Hi @RossBoylan 

Is there a reason for this to be in github.com and not UCSF github?. the breastdb mentioned in this repo does not exist anywhere in the public internet. This is internal to UCSF Radiology.

Are there plans to make the database accessible to a public audience in the future?

**Comment by RossBoylan** [comment]
It's on the public github, albeit under radiology-research, so that local users who are not registered with UCSF github can access it more easily.  As the last sentence of the introductory README says "If you are not in UCSF Radiology, it is very unlikely this package is of interest."

It also fits better with registering the package on PyPI, also publicly accessible.

There is no patient data in any of the files.  And there are no plans (AFAIK) to make the ispy2 data publicly available.

Ross

________________________________________
From: jedchan ***@***.***>
Sent: Thursday, October 12, 2023 6:46 PM
To: radiology-research/ispy2_mri
Cc: Boylan, Ross; Mention
Subject: [radiology-research/ispy2_mri] breastdb issue (Issue #2)

Hi @RossBoylan Is there a reason for this to be in github. com and not UCSF github?. the breastdb mentioned in this repo does not exist anywhere in the public internet. This is internal to UCSF Radiology. Are there plans to make the database
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Hi @RossBoylan<https://urldefense.com/v3/__https://github.com/RossBoylan__;!!LQC6Cpwp!trR6ZVBgrAngKTShFsh2RWKndmF_lI9AxE3eG9RaLu9KzomW6X37mx6H-cHjnDTMGODDcfGbu2LQDFZVckMCEaW4x48$>

Is there a reason for this to be in github.com and not UCSF github?. the breastdb mentioned in this repo does not exist anywhere in the public internet. This is internal to UCSF Radiology.

Are there plans to make the database accessible to a public audience in the future?

**Comment by jedchan** [comment]
Thanks. I'm still trying to wrap my head around how this will work, but if the code is going to be added to pypi, then this makes sense for it to be public.
